spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
    check-location: true
    locations: classpath:db/migration/common
    clean-disabled: false
    clean-on-validation-error: false
    url: jdbc:postgresql://localhost:5432/postgres
    schemas: sample_flyway
    user: postgres
    password: pass@123
    create-schemas: false
    init-sqls: CREATE SCHEMA IF NOT EXISTS sample_flyway