spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: pass@123
  profiles:
    active: prod
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: postgresql
