INSERT INTO USERS (ID, USER_NAME) VALUES (1, 'DEV TEST USER 1');
INSERT INTO USERS (ID, USER_NAME) VALUES (2, 'DEV TEST USER 2');
INSERT INTO USERS (ID, USER_NAME) VALUES (3, 'DEV TEST USER 3');
INSERT INTO USERS (ID, USER_NAME) VALUES (4, 'DEV TEST USER 4');
INSERT INTO USERS (ID, USER_NAME) VALUES (5, 'DEV TEST USER 5');
